license="GNU GPLv3"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/TeamPneumatic/pnc-repressurized/issues"
displayURL="https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized"
logoFile="pncr_logo.png"
credits=""
authors="desht, MineMaarten"

[[mods]]
    modId="pneumaticcraft"
    version="6.0.20+mc1.20.1"
    displayName="PneumaticCraft: Repressurized"
    updateJSONURL="https://raw.githubusercontent.com/TeamPneumatic/pnc-repressurized/1.20.1/release_info.json" #optional
    description='''
PneumaticCraft: Repressurized: doing cool stuff with compressed air.'''

[[dependencies.pneumaticcraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.20.1-80,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pneumaticcraft]]
    modId="jei"
    mandatory=false
    versionRange="[13.1.0,)"
    ordering="NONE"
    side="BOTH"
